;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        cua-cut-region
        cua-paste
        dired-toggle-read-only
        end-of-buffer
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-join-sexps
        paredit-newline
        paredit-split-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        text-scale-increase
        ))
